# Generated by Django 6.0.5 on 2026-05-19 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name="Language Code (e.g., 'en', 'es')")),
                ('name', models.CharField(max_length=50, verbose_name='Language Name')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=100, verbose_name='Original Word')),
                ('translation', models.CharField(max_length=100, verbose_name='Translation')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.language', verbose_name='Language')),
            ],
        ),
    ]
