# Generated by Django 6.0.5 on 2026-05-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano')], default='es', max_length=2),
        ),
    ]
