# Generated by Django 6.0.5 on 2026-05-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_word_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('sp', 'Spanish'), ('en', 'English'), ('pl', 'Polski')], default='es', max_length=2),
        ),
    ]
